In [1]:
import kagglehub
path = kagglehub.dataset_download("fedesoriano/company-bankruptcy-prediction")

Downloading to /root/.cache/kagglehub/datasets/fedesoriano/company-bankruptcy-prediction/2.archive...

100%|██████████| 4.63M/4.63M [00:00<00:00, 85.6MB/s]

Extracting files...

In [2]:
import os
import pandas as pd

# List files in the downloaded directory to find the dataset file
files_in_path = os.listdir(path)
print(f"Files in downloaded path: {files_in_path}")

# Assuming the main data file is a CSV and identifiable, load it
# This might need adjustment based on the actual file name found
data_file = next((f for f in files_in_path if f.endswith('.csv')), None)

if data_file:
    df = pd.read_csv(os.path.join(path, data_file))
    print("\nDataset loaded successfully. Displaying the first 5 rows:")
    display(df.head())
else:
    print("No CSV file found in the downloaded dataset path.")

Files in downloaded path: ['data.csv']

Dataset loaded successfully. Displaying the first 5 rows:

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490

In [3]:
# Display basic information about the dataset
print("\nDataset Info:")
df.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6819 entries, 0 to 6818
Data columns (total 96 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Bankrupt?                                                 6819 non-null   int64
 1    ROA(C) before interest and depreciation before interest  6819 non-null   float64
 2    ROA(A) before interest and % after tax                   6819 non-null   float64
 3    ROA(B) before interest and depreciation after tax        6819 non-null   float64
 4    Operating Gross Margin                                   6819 non-null   float64
 5    Realized Sales Gross Margin                              6819 non-null   float64
 6    Operating Profit Rate                                    6819 non-null   float64
 7    Pre-tax net Interest Rate                                6819 non-null   float64
 8    After-tax net Interest Rate                              6819 non-null   float64
 9    Non-industry income and expenditure/revenue              6819 non-null   float64
 10   Continuous interest rate (after tax)                     6819 non-null   float64
 11   Operating Expense Rate                                   6819 non-null   float64
 12   Research and development expense rate                    6819 non-null   float64
 13   Cash flow rate                                           6819 non-null   float64
 14   Interest-bearing debt interest rate                      6819 non-null   float64
 15   Tax rate (A)                                             6819 non-null   float64
 16   Net Value Per Share (B)                                  6819 non-null   float64
 17   Net Value Per Share (A)                                  6819 non-null   float64
 18   Net Value Per Share (C)                                  6819 non-null   float64
 19   Persistent EPS in the Last Four Seasons                  6819 non-null   float64
 20   Cash Flow Per Share                                      6819 non-null   float64
 21   Revenue Per Share (Yuan ¥)                               6819 non-null   float64
 22   Operating Profit Per Share (Yuan ¥)                      6819 non-null   float64
 23   Per Share Net profit before tax (Yuan ¥)                 6819 non-null   float64
 24   Realized Sales Gross Profit Growth Rate                  6819 non-null   float64
 25   Operating Profit Growth Rate                             6819 non-null   float64
 26   After-tax Net Profit Growth Rate                         6819 non-null   float64
 27   Regular Net Profit Growth Rate                           6819 non-null   float64
 28   Continuous Net Profit Growth Rate                        6819 non-null   float64
 29   Total Asset Growth Rate                                  6819 non-null   float64
 30   Net Value Growth Rate                                    6819 non-null   float64
 31   Total Asset Return Growth Rate Ratio                     6819 non-null   float64
 32   Cash Reinvestment %                                      6819 non-null   float64
 33   Current Ratio                                            6819 non-null   float64
 34   Quick Ratio                                              6819 non-null   float64
 35   Interest Expense Ratio                                   6819 non-null   float64
 36   Total debt/Total net worth                               6819 non-null   float64
 37   Debt ratio %                                             6819 non-null   float64
 38   Net worth/Assets                                         6819 non-null   float64
 39   Long-term fund suitability ratio (A)                     6819 non-null   float64
 40   Borrowing dependency                                     6819 non-null   float64
 41   Contingent liabilities/Net worth                         6819 non-null   float64
 42   Operating profit/Paid-in capital                         6819 non-null   float64
 43   Net profit before tax/Paid-in capital                    6819 non-null   float64
 44   Inventory and accounts receivable/Net value              6819 non-null   float64
 45   Total Asset Turnover                                     6819 non-null   float64
 46   Accounts Receivable Turnover                             6819 non-null   float64
 47   Average Collection Days                                  6819 non-null   float64
 48   Inventory Turnover Rate (times)                          6819 non-null   float64
 49   Fixed Assets Turnover Frequency                          6819 non-null   float64
 50   Net Worth Turnover Rate (times)                          6819 non-null   float64
 51   Revenue per person                                       6819 non-null   float64
 52   Operating profit per person                              6819 non-null   float64
 53   Allocation rate per person                               6819 non-null   float64
 54   Working Capital to Total Assets                          6819 non-null   float64
 55   Quick Assets/Total Assets                                6819 non-null   float64
 56   Current Assets/Total Assets                              6819 non-null   float64
 57   Cash/Total Assets                                        6819 non-null   float64
 58   Quick Assets/Current Liability                           6819 non-null   float64
 59   Cash/Current Liability                                   6819 non-null   float64
 60   Current Liability to Assets                              6819 non-null   float64
 61   Operating Funds to Liability                             6819 non-null   float64
 62   Inventory/Working Capital                                6819 non-null   float64
 63   Inventory/Current Liability                              6819 non-null   float64
 64   Current Liabilities/Liability                            6819 non-null   float64
 65   Working Capital/Equity                                   6819 non-null   float64
 66   Current Liabilities/Equity                               6819 non-null   float64
 67   Long-term Liability to Current Assets                    6819 non-null   float64
 68   Retained Earnings to Total Assets                        6819 non-null   float64
 69   Total income/Total expense                               6819 non-null   float64
 70   Total expense/Assets                                     6819 non-null   float64
 71   Current Asset Turnover Rate                              6819 non-null   float64
 72   Quick Asset Turnover Rate                                6819 non-null   float64
 73   Working capitcal Turnover Rate                           6819 non-null   float64
 74   Cash Turnover Rate                                       6819 non-null   float64
 75   Cash Flow to Sales                                       6819 non-null   float64
 76   Fixed Assets to Assets                                   6819 non-null   float64
 77   Current Liability to Liability                           6819 non-null   float64
 78   Current Liability to Equity                              6819 non-null   float64
 79   Equity to Long-term Liability                            6819 non-null   float64
 80   Cash Flow to Total Assets                                6819 non-null   float64
 81   Cash Flow to Liability                                   6819 non-null   float64
 82   CFO to Assets                                            6819 non-null   float64
 83   Cash Flow to Equity                                      6819 non-null   float64
 84   Current Liability to Current Assets                      6819 non-null   float64
 85   Liability-Assets Flag                                    6819 non-null   int64
 86   Net Income to Total Assets                               6819 non-null   float64
 87   Total assets to GNP price                                6819 non-null   float64
 88   No-credit Interval                                       6819 non-null   float64
 89   Gross Profit to Sales                                    6819 non-null   float64
 90   Net Income to Stockholder's Equity                       6819 non-null   float64
 91   Liability to Equity                                      6819 non-null   float64
 92   Degree of Financial Leverage (DFL)                       6819 non-null   float64
 93   Interest Coverage Ratio (Interest expense to EBIT)       6819 non-null   float64
 94   Net Income Flag                                          6819 non-null   int64
 95   Equity to Liability                                      6819 non-null   float64
dtypes: float64(93), int64(3)
memory usage: 5.0 MB

In [4]:
# Display descriptive statistics for numerical columns
print("\nDescriptive Statistics:")
display(df.describe())

Descriptive Statistics:

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
count,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,...,6819.000000,6.819000e+03,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.0,6819.000000
mean,0.032263,0.505180,0.558625,0.553589,0.607948,0.607929,0.998755,0.797190,0.809084,0.303623,...,0.807760,1.862942e+07,0.623915,0.607946,0.840402,0.280365,0.027541,0.565358,1.0,0.047578
std,0.176710,0.060686,0.065620,0.061595,0.016934,0.016916,0.013010,0.012869,0.013601,0.011163,...,0.040332,3.764501e+08,0.012290,0.016934,0.014523,0.014463,0.015668,0.013214,0.0,0.050014
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000
25%,0.000000,0.476527,0.535543,0.527277,0.600445,0.600434,0.998969,0.797386,0.809312,0.303466,...,0.796750,9.036205e-04,0.623636,0.600443,0.840115,0.276944,0.026791,0.565158,1.0,0.024477
50%,0.000000,0.502706,0.559802,0.552278,0.605997,0.605976,0.999022,0.797464,0.809375,0.303525,...,0.810619,2.085213e-03,0.623879,0.605998,0.841179,0.278778,0.026808,0.565252,1.0,0.033798
75%,0.000000,0.535563,0.589157,0.584105,0.613914,0.613842,0.999095,0.797579,0.809469,0.303585,...,0.826455,5.269777e-03,0.624168,0.613913,0.842357,0.281449,0.026913,0.565725,1.0,0.052838
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,9.820000e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000

In [5]:
# Clean column names: remove leading/trailing spaces
df.columns = df.columns.str.strip()

# Display cleaned column names and check for 'Bankrupt?'
print("Cleaned Column Names:")
print(df.columns)

# Separate features (X) and target (y)
X = df.drop('Bankrupt?', axis=1)
y = df['Bankrupt?']

print(f"\nShape of features (X): {X.shape}")
print(f"Shape of target (y): {y.shape}")

Cleaned Column Names:
Index(['Bankrupt?', 'ROA(C) before interest and depreciation before interest',
       'ROA(A) before interest and % after tax',
       'ROA(B) before interest and depreciation after tax',
       'Operating Gross Margin', 'Realized Sales Gross Margin',
       'Operating Profit Rate', 'Pre-tax net Interest Rate',
       'After-tax net Interest Rate',
       'Non-industry income and expenditure/revenue',
       'Continuous interest rate (after tax)', 'Operating Expense Rate',
       'Research and development expense rate', 'Cash flow rate',
       'Interest-bearing debt interest rate', 'Tax rate (A)',
       'Net Value Per Share (B)', 'Net Value Per Share (A)',
       'Net Value Per Share (C)', 'Persistent EPS in the Last Four Seasons',
       'Cash Flow Per Share', 'Revenue Per Share (Yuan ¥)',
       'Operating Profit Per Share (Yuan ¥)',
       'Per Share Net profit before tax (Yuan ¥)',
       'Realized Sales Gross Profit Growth Rate',
       'Operating Profit Growth Rate', 'After-tax Net Profit Growth Rate',
       'Regular Net Profit Growth Rate', 'Continuous Net Profit Growth Rate',
       'Total Asset Growth Rate', 'Net Value Growth Rate',
       'Total Asset Return Growth Rate Ratio', 'Cash Reinvestment %',
       'Current Ratio', 'Quick Ratio', 'Interest Expense Ratio',
       'Total debt/Total net worth', 'Debt ratio %', 'Net worth/Assets',
       'Long-term fund suitability ratio (A)', 'Borrowing dependency',
       'Contingent liabilities/Net worth', 'Operating profit/Paid-in capital',
       'Net profit before tax/Paid-in capital',
       'Inventory and accounts receivable/Net value', 'Total Asset Turnover',
       'Accounts Receivable Turnover', 'Average Collection Days',
       'Inventory Turnover Rate (times)', 'Fixed Assets Turnover Frequency',
       'Net Worth Turnover Rate (times)', 'Revenue per person',
       'Operating profit per person', 'Allocation rate per person',
       'Working Capital to Total Assets', 'Quick Assets/Total Assets',
       'Current Assets/Total Assets', 'Cash/Total Assets',
       'Quick Assets/Current Liability', 'Cash/Current Liability',
       'Current Liability to Assets', 'Operating Funds to Liability',
       'Inventory/Working Capital', 'Inventory/Current Liability',
       'Current Liabilities/Liability', 'Working Capital/Equity',
       'Current Liabilities/Equity', 'Long-term Liability to Current Assets',
       'Retained Earnings to Total Assets', 'Total income/Total expense',
       'Total expense/Assets', 'Current Asset Turnover Rate',
       'Quick Asset Turnover Rate', 'Working capitcal Turnover Rate',
       'Cash Turnover Rate', 'Cash Flow to Sales', 'Fixed Assets to Assets',
       'Current Liability to Liability', 'Current Liability to Equity',
       'Equity to Long-term Liability', 'Cash Flow to Total Assets',
       'Cash Flow to Liability', 'CFO to Assets', 'Cash Flow to Equity',
       'Current Liability to Current Assets', 'Liability-Assets Flag',
       'Net Income to Total Assets', 'Total assets to GNP price',
       'No-credit Interval', 'Gross Profit to Sales',
       'Net Income to Stockholder's Equity', 'Liability to Equity',
       'Degree of Financial Leverage (DFL)',
       'Interest Coverage Ratio (Interest expense to EBIT)', 'Net Income Flag',
       'Equity to Liability'],
      dtype='object')

Shape of features (X): (6819, 95)
Shape of target (y): (6819,)

In [6]:
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale the features
X_scaled = scaler.fit_transform(X)

# Convert scaled features back to a DataFrame for easier inspection
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

print("\nFeatures scaled successfully. Displaying first 5 rows of scaled features:")
display(X_scaled_df.head())

Features scaled successfully. Displaying first 5 rows of scaled features:

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,-2.217909,-2.045798,-2.400361,-0.383334,-0.382638,0.016456,-0.023516,-0.020165,-0.087479,-0.031281,...,-2.254317,-0.049491,-0.084274,-0.383465,-0.861611,0.680171,-0.060031,-0.098978,0.0,-0.622067
1,-0.673828,-0.311068,-0.598450,0.135068,0.136307,0.014671,0.014799,0.015966,-0.005957,0.009823,...,-0.309033,-0.049491,-0.021388,0.135253,-0.029804,0.240685,15.129816,0.364559,0.0,-0.535573
2,-1.303672,-0.908420,-1.319910,-0.383759,-0.388177,0.007858,-0.061111,-0.051183,-0.142238,-0.086566,...,-0.820510,-0.049491,-0.005984,-0.383698,-0.249820,0.679247,-0.062961,-0.125015,0.0,-0.621960
3,-1.735886,-1.636209,-1.556340,-1.441418,-1.441832,-0.004257,-0.017313,-0.008676,-0.024491,-0.011077,...,-1.691222,-0.049491,-0.080226,-1.441526,-0.392864,0.093765,-0.053903,-0.052562,0.0,-0.471826
4,-0.661778,-0.307745,-0.508050,-0.541238,-0.540708,0.016758,0.013703,0.016186,-0.013254,0.013300,...,-0.316008,-0.049491,-0.032052,-0.541255,-0.029564,-0.128014,-0.178037,0.776395,0.0,-0.241715

In [7]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (5455, 95)
Shape of X_test: (1364, 95)
Shape of y_train: (5455,)
Shape of y_test: (1364,)

In [8]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Define the deep learning model
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),  # Input layer with number of features
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3), # Added dropout for regularization
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.3), # Added dropout for regularization
    layers.Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Display model summary
print("Deep Learning Model Summary:")
model.summary()

Deep Learning Model Summary:

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │        12,288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 20,609 (80.50 KB)

 Trainable params: 20,609 (80.50 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
# Train the model
print("\nTraining the Deep Learning Model...")
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=1)

print("\nModel training complete.")

Training the Deep Learning Model...
Epoch 1/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9576 - loss: 0.1901 - val_accuracy: 0.9661 - val_loss: 0.0950
Epoch 2/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9681 - loss: 0.1069 - val_accuracy: 0.9661 - val_loss: 0.0959
Epoch 3/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9711 - loss: 0.0918 - val_accuracy: 0.9670 - val_loss: 0.0949
Epoch 4/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9730 - loss: 0.0805 - val_accuracy: 0.9661 - val_loss: 0.0974
Epoch 5/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9723 - loss: 0.0783 - val_accuracy: 0.9624 - val_loss: 0.0971
Epoch 6/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9736 - loss: 0.0760 - val_accuracy: 0.9679 - val_loss: 0.0963
Epoch 7/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9718 - loss: 0.0701 - val_accuracy: 0.9652 - val_loss: 0.1022
Epoch 8/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9736 - loss: 0.0670 - val_accuracy: 0.9661 - val_loss: 0.0951
Epoch 9/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9757 - loss: 0.0638 - val_accuracy: 0.9661 - val_loss: 0.0942
Epoch 10/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9743 - loss: 0.0657 - val_accuracy: 0.9643 - val_loss: 0.0994
Epoch 11/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9762 - loss: 0.0599 - val_accuracy: 0.9652 - val_loss: 0.0974
Epoch 12/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9748 - loss: 0.0580 - val_accuracy: 0.9670 - val_loss: 0.1002
Epoch 13/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9773 - loss: 0.0558 - val_accuracy: 0.9652 - val_loss: 0.0981
Epoch 14/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9764 - loss: 0.0566 - val_accuracy: 0.9661 - val_loss: 0.1021
Epoch 15/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9787 - loss: 0.0513 - val_accuracy: 0.9643 - val_loss: 0.1093
Epoch 16/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9803 - loss: 0.0491 - val_accuracy: 0.9670 - val_loss: 0.1061
Epoch 17/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9817 - loss: 0.0483 - val_accuracy: 0.9643 - val_loss: 0.1007
Epoch 18/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9828 - loss: 0.0455 - val_accuracy: 0.9661 - val_loss: 0.1054
Epoch 19/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9824 - loss: 0.0426 - val_accuracy: 0.9652 - val_loss: 0.1048
Epoch 20/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9842 - loss: 0.0447 - val_accuracy: 0.9652 - val_loss: 0.1143
Epoch 21/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9819 - loss: 0.0416 - val_accuracy: 0.9652 - val_loss: 0.1314
Epoch 22/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9835 - loss: 0.0418 - val_accuracy: 0.9661 - val_loss: 0.1165
Epoch 23/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9849 - loss: 0.0396 - val_accuracy: 0.9624 - val_loss: 0.1349
Epoch 24/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9860 - loss: 0.0377 - val_accuracy: 0.9624 - val_loss: 0.1257
Epoch 25/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9856 - loss: 0.0376 - val_accuracy: 0.9661 - val_loss: 0.1188
Epoch 26/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9879 - loss: 0.0340 - val_accuracy: 0.9624 - val_loss: 0.1364
Epoch 27/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9883 - loss: 0.0315 - val_accuracy: 0.9652 - val_loss: 0.1373
Epoch 28/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9895 - loss: 0.0320 - val_accuracy: 0.9652 - val_loss: 0.1466
Epoch 29/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9885 - loss: 0.0311 - val_accuracy: 0.9652 - val_loss: 0.1302
Epoch 30/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9876 - loss: 0.0304 - val_accuracy: 0.9652 - val_loss: 0.1371
Epoch 31/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9865 - loss: 0.0350 - val_accuracy: 0.9661 - val_loss: 0.1466
Epoch 32/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9901 - loss: 0.0292 - val_accuracy: 0.9661 - val_loss: 0.1569
Epoch 33/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9895 - loss: 0.0258 - val_accuracy: 0.9661 - val_loss: 0.1607
Epoch 34/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9904 - loss: 0.0236 - val_accuracy: 0.9643 - val_loss: 0.1658
Epoch 35/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9908 - loss: 0.0276 - val_accuracy: 0.9679 - val_loss: 0.1775
Epoch 36/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9929 - loss: 0.0245 - val_accuracy: 0.9652 - val_loss: 0.1958
Epoch 37/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9899 - loss: 0.0301 - val_accuracy: 0.9643 - val_loss: 0.1948
Epoch 38/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9906 - loss: 0.0276 - val_accuracy: 0.9643 - val_loss: 0.1748
Epoch 39/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9924 - loss: 0.0284 - val_accuracy: 0.9633 - val_loss: 0.1908
Epoch 40/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9924 - loss: 0.0240 - val_accuracy: 0.9633 - val_loss: 0.2014
Epoch 41/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9934 - loss: 0.0185 - val_accuracy: 0.9624 - val_loss: 0.2146
Epoch 42/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9936 - loss: 0.0184 - val_accuracy: 0.9652 - val_loss: 0.2156
Epoch 43/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9968 - loss: 0.0147 - val_accuracy: 0.9624 - val_loss: 0.2354
Epoch 44/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9915 - loss: 0.0216 - val_accuracy: 0.9661 - val_loss: 0.2232
Epoch 45/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9952 - loss: 0.0158 - val_accuracy: 0.9643 - val_loss: 0.2414
Epoch 46/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9940 - loss: 0.0178 - val_accuracy: 0.9661 - val_loss: 0.2467
Epoch 47/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9936 - loss: 0.0160 - val_accuracy: 0.9643 - val_loss: 0.2618
Epoch 48/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9943 - loss: 0.0142 - val_accuracy: 0.9643 - val_loss: 0.2476
Epoch 49/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9947 - loss: 0.0151 - val_accuracy: 0.9652 - val_loss: 0.2557
Epoch 50/50
137/137 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9934 - loss: 0.0214 - val_accuracy: 0.9661 - val_loss: 0.2685

Model training complete.

In [10]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# Predict probabilities on the test set
y_pred_proba = model.predict(X_test)
# Convert probabilities to binary predictions (0 or 1)
y_pred = np.round(y_pred_proba).flatten()

# Calculate additional metrics
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"\nPrecision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print("Confusion Matrix:\n", conf_matrix)

Test Loss: 0.5671
Test Accuracy: 0.9604
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

Precision: 0.4444
Recall: 0.2353
F1 Score: 0.3077
Confusion Matrix:
 [[1298   15]
 [  39   12]]

In [11]:
import joblib
import os

# Define paths to save the model and scaler
model_path = 'bankruptcy_model.keras'
scaler_path = 'scaler.pkl'

# Save the Keras model
model.save(model_path)
print(f"Deep learning model saved to {model_path}")

# Save the StandardScaler
joblib.dump(scaler, scaler_path)
print(f"StandardScaler saved to {scaler_path}")

Deep learning model saved to bankruptcy_model.keras
StandardScaler saved to scaler.pkl

Now that the model and scaler are saved, let's create the Streamlit application file `app.py`.

In [12]:
%%writefile app.py

import streamlit as st
import pandas as pd
import numpy as np
import tensorflow as tf
import joblib
import os

# --- Load the Model and Scaler ---

# Use st.cache_resource for heavy objects like models to load them only once
@st.cache_resource
def load_resources():
    model_path = 'bankruptcy_model.keras'
    scaler_path = 'scaler.pkl'

    # Check if files exist
    if not os.path.exists(model_path):
        st.error(f"Model file not found at {model_path}. Please ensure it is saved.")
        st.stop()
    if not os.path.exists(scaler_path):
        st.error(f"Scaler file not found at {scaler_path}. Please ensure it is saved.")
        st.stop()

    model = tf.keras.models.load_model(model_path)
    scaler = joblib.load(scaler_path)
    return model, scaler

model, scaler = load_resources()

# --- Streamlit App Layout ---
st.set_page_config(page_title="Company Bankruptcy Predictor 📉", layout="wide")

st.title("Company Bankruptcy Predictor 📈")
st.markdown("### Will your company thrive or dive? Let's find out! ✨")
st.write("Enter the financial indicators below to predict the likelihood of bankruptcy. 📊")

# Create a dictionary to store feature default values (mean of original X for demonstration)
# In a real scenario, you'd calculate these from your original training data.
feature_means = {
    'ROA(C) before interest and depreciation before interest': 0.505180, 'ROA(A) before interest and % after tax': 0.558625,
    'ROA(B) before interest and depreciation after tax': 0.553589, 'Operating Gross Margin': 0.607948,
    'Realized Sales Gross Margin': 0.607929, 'Operating Profit Rate': 0.998755,
    'Pre-tax net Interest Rate': 0.797190, 'After-tax net Interest Rate': 0.809084,
    'Non-industry income and expenditure/revenue': 0.303623, 'Continuous interest rate (after tax)': 0.780416,
    'Operating Expense Rate': 1.095450, 'Research and development expense rate': 0.000976,
    'Cash flow rate': 0.671531, 'Interest-bearing debt interest rate': 0.064041,
    'Tax rate (A)': 0.040280, 'Net Value Per Share (B)': 0.034443,
    'Net Value Per Share (A)': 0.035760, 'Net Value Per Share (C)': 0.034433,
    'Persistent EPS in the Last Four Seasons': 0.226685, 'Cash Flow Per Share': 0.323482,
    'Revenue Per Share (Yuan ¥)': 1.328641, 'Operating Profit Per Share (Yuan ¥)': 0.109091,
    'Per Share Net profit before tax (Yuan ¥)': 0.084863, 'Realized Sales Gross Profit Growth Rate': 0.022408,
    'Operating Profit Growth Rate': 0.840268, 'After-tax Net Profit Growth Rate': 0.835943,
    'Regular Net Profit Growth Rate': 0.834057, 'Continuous Net Profit Growth Rate': 0.839816,
    'Total Asset Growth Rate': 0.264960, 'Net Value Growth Rate': 0.040393,
    'Total Asset Return Growth Rate Ratio': 0.840374, 'Cash Reinvestment %': 0.312915,
    'Current Ratio': 0.403285, 'Quick Ratio': 0.837659, 'Interest Expense Ratio': 0.630991,
    'Total debt/Total net worth': 0.006272, 'Debt ratio %': 0.113264, 'Net worth/Assets': 0.875249,
    'Long-term fund suitability ratio (A)': 0.000329, 'Borrowing dependency': 0.032348,
    'Contingent liabilities/Net worth': 0.009714, 'Operating profit/Paid-in capital': 0.112104,
    'Net profit before tax/Paid-in capital': 0.087455, 'Inventory and accounts receivable/Net value': 0.403803,
    'Total Asset Turnover': 0.642959, 'Accounts Receivable Turnover': 0.009618, 'Average Collection Days': 0.621497,
    'Inventory Turnover Rate (times)': 0.090176, 'Fixed Assets Turnover Frequency': 1.082719, 'Net Worth Turnover Rate (times)': 0.119561,
    'Revenue per person': 0.386445, 'Operating profit per person': 0.126915, 'Allocation rate per person': 0.021591,
    'Working Capital to Total Assets': 0.760049, 'Quick Assets/Total Assets': 0.596000, 'Current Assets/Total Assets': 0.760603,
    'Cash/Total Assets': 0.124095, 'Quick Assets/Current Liability': 0.359287, 'Cash/Current Liability': 0.119428,
    'Current Liability to Assets': 0.294700, 'Operating Funds to Liability': 0.320491, 'Inventory/Working Capital': 0.019584,
    'Inventory/Current Liability': 0.038053, 'Current Liabilities/Liability': 0.287843, 'Working Capital/Equity': 0.002824,
    'Current Liabilities/Equity': 0.027541, 'Long-term Liability to Current Assets': 0.000030, 'Retained Earnings to Total Assets': 0.904068,
    'Total income/Total expense': 0.000458, 'Total expense/Assets': 0.000315, 'Current Asset Turnover Rate': 0.002529,
    'Quick Asset Turnover Rate': 0.000780, 'Working capitcal Turnover Rate': 0.006309, 'Cash Turnover Rate': 0.003185,
    'Cash Flow to Sales': 0.326225, 'Fixed Assets to Assets': 0.584347, 'Current Liability to Liability': 0.021062,
    'Current Liability to Equity': 0.031528, 'Equity to Long-term Liability': 0.009581, 'Cash Flow to Total Assets': 0.315049,
    'Cash Flow to Liability': 0.047690, 'CFO to Assets': 0.315570, 'Cash Flow to Equity': 0.529409,
    'Current Liability to Current Assets': 0.038531, 'Liability-Assets Flag': 0.001173, 'Net Income to Total Assets': 0.807760,
    'Total assets to GNP price': 1.862942e+07, 'No-credit Interval': 0.623795, 'Gross Profit to Sales': 0.607946,
    'Net Income to Stockholder\'s Equity': 0.840402, 'Liability to Equity': 0.280336, 'Degree of Financial Leverage (DFL)': 0.026601,
    'Interest Coverage Ratio (Interest expense to EBIT)': 0.565358, 'Net Income Flag': 1.0, 'Equity to Liability': 0.047578
}

# Sidebar for Inputs
st.sidebar.header("Financial Indicators Input 📝")
input_data = {}

# Dynamically create input fields for all 95 features
# Note: For a real app, you might categorize these or offer file upload for many features.
for feature, mean_value in feature_means.items():
    # Using a simple number input. In practice, you might want more specific ranges or types.
    input_data[feature] = st.sidebar.number_input(
        f"Enter value for {feature}:",
        value=float(mean_value), # Use mean as default
        step=0.01, # Allow small increments
        format="%.6f", # Format to show decimals
        key=feature # Unique key for each widget
    )

# Prediction Button
if st.button("Predict Bankruptcy Status 🔮"):
    # Convert input data to DataFrame
    input_df = pd.DataFrame([input_data])

    # Scale the input data using the loaded scaler
    scaled_input = scaler.transform(input_df)

    # Make prediction
    prediction_proba = model.predict(scaled_input)[0][0]
    prediction_class = (prediction_proba > 0.5).astype(int)

    st.subheader("Prediction Result 🚀")
    if prediction_class == 1:
        st.error(f"### 🚨 Warning: High Risk of Bankruptcy! (Probability: {prediction_proba:.2%}) 📉")
        st.balloons()
    else:
        st.success(f"### 🎉 Good News: Low Risk of Bankruptcy! (Probability: {prediction_proba:.2%}) ⬆️")
        st.snow()

    st.write("Please remember this is a model prediction and should be used for informational purposes only. Consult with financial experts for critical decisions. 🤝")

# --- Instructions to run the app ---
st.markdown("\n---")
st.markdown("### To run this Streamlit app:")
st.code("streamlit run app.py")
st.write("Make sure you have Streamlit installed (`pip install streamlit`).")

Writing app.py

In [13]:
!pip install --ignore-installed blinker
!pip install streamlit

Collecting blinker
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Installing collected packages: blinker
Successfully installed blinker-1.9.0
Collecting streamlit
  Downloading streamlit-1.64.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.53.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.26.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.64.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 54.5 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 78.3 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.64.0

In [14]:
!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.13/dist-packages (1.64.0)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (8.5.0)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from streamlit) (26.3)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.53.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.13/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.26.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.0.0->streamlit) (3.19)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.27->streamlit) (2026.7.22)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [15]:
from pyngrok import ngrok
ngrok.set_auth_token("3H2nxZtP4iC5L9tX9K97OPLut9W_4JsZrRVF5aRFQpQCCePy1")

In [16]:
from pyngrok import ngrok

public_url = ngrok.connect(8501)
print(public_url)

NgrokTunnel: "https://vanity-amperage-commodore.ngrok-free.dev" -> "http://localhost:8501"

In [17]:
# Run the Streamlit app
# This will provide a public URL to access the app
!streamlit run app.py &

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-10-02 15:38:56.613 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.57.205.229:8501

2026-10-02 15:39:19.086517: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
  Stopping...